services:
  db:
    image: mariadb:latest
    environment:
      # ตั้งรหัสผ่านเป็น root (หรืออะไรก็ได้ที่คุณชอบ)
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ll2_hotel
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    ports:
      - '8080:8080'
